### ISSUE TITLE
Set Tableau Vis to Resize to Proper View

### ISSUE THREAD

**Issue by stevenkotansky** [BlubbrDev/site#12]

**Comment by sorenrood** [comment]
We should be able to do this today.

**Comment by notjustinshaw** [comment]
@sorenrood @stevenkotansky I checked it out and I'm working on it now

**Comment by notjustinshaw** [comment]
![Screen Shot 2021-03-05 at 9 32 28 AM](https://user-images.githubusercontent.com/46334750/110151761-b712e500-7d95-11eb-9a6f-cd4db0f26684.png)
How's that @sorenrood and @stevenkotansky
