### ISSUE TITLE
blubbr.io/discord

### ISSUE THREAD

**Issue by sorenrood** [BlubbrDev/site#3]
As of now, if we want to send someone a discord invite link, we have to send this ugly link: [https://discord.gg/ZtAWMP2DDd](https://discord.gg/ZtAWMP2DDd) (This exact link will never expire).

It would be great if `blubbr.io/discord` pointed to the above link.

**Comment by notjustinshaw** [comment]
I think I can do that in our DNS settings in Google Domains. Would you rather have `discord.blubbr.io` or `blubbr.io/discord` @sorenrood?

**Comment by sorenrood** [comment]
> I think I can do that in our DNS settings in Google Domains. Would you rather have `discord.blubbr.io` or `blubbr.io/discord` @sorenrood?

As of now I think I like `blubbr.io/discord` more @justinalexandershaw.

**Comment by notjustinshaw** [comment]
Okay I'm gonna check this out and get started @sorenrood

**Comment by sorenrood** [comment]
> Okay I'm gonna check this out and get started @sorenrood

Sweet @justinalexandershaw! :smile:
